#!/usr/bin/env python3
"""Scan a repository and emit a compact JSON map for code research."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
from typing import Any, Iterable

try:
    import tomllib
except ModuleNotFoundError:  # pragma: no cover - Python < 3.11 fallback
    tomllib = None  # type: ignore[assignment]


SKIP_DIRS = {
    ".git",
    ".hg",
    ".svn",
    ".idea",
    ".vscode",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    ".next",
    ".nuxt",
    ".svelte-kit",
    ".turbo",
    ".cache",
    "node_modules",
    "bower_components",
    "vendor",
    "dist",
    "build",
    "coverage",
    "target",
    "out",
    ".tox",
    ".venv",
    "venv",
    "env",
}

SKIP_SUFFIXES = {
    ".png",
    ".jpg",
    ".jpeg",
    ".gif",
    ".webp",
    ".ico",
    ".pdf",
    ".zip",
    ".tar",
    ".gz",
    ".bz2",
    ".xz",
    ".7z",
    ".woff",
    ".woff2",
    ".ttf",
    ".otf",
    ".pyc",
    ".class",
    ".jar",
    ".wasm",
}

LANG_BY_SUFFIX = {
    ".py": "Python",
    ".js": "JavaScript",
    ".jsx": "JavaScript",
    ".ts": "TypeScript",
    ".tsx": "TypeScript",
    ".mjs": "JavaScript",
    ".cjs": "JavaScript",
    ".go": "Go",
    ".rs": "Rust",
    ".java": "Java",
    ".kt": "Kotlin",
    ".kts": "Kotlin",
    ".swift": "Swift",
    ".c": "C",
    ".h": "C/C++",
    ".cc": "C++",
    ".cpp": "C++",
    ".hpp": "C++",
    ".cs": "C#",
    ".rb": "Ruby",
    ".php": "PHP",
    ".ex": "Elixir",
    ".exs": "Elixir",
    ".erl": "Erlang",
    ".scala": "Scala",
    ".clj": "Clojure",
    ".lua": "Lua",
    ".r": "R",
    ".R": "R",
    ".sh": "Shell",
    ".bash": "Shell",
    ".zsh": "Shell",
    ".fish": "Shell",
    ".sql": "SQL",
    ".html": "HTML",
    ".css": "CSS",
    ".scss": "CSS",
    ".md": "Markdown",
}

MANIFEST_TYPES = {
    "package.json": "node-package",
    "pnpm-workspace.yaml": "node-workspace",
    "yarn.lock": "node-lockfile",
    "pnpm-lock.yaml": "node-lockfile",
    "package-lock.json": "node-lockfile",
    "requirements.txt": "python-requirements",
    "pyproject.toml": "python-project",
    "setup.py": "python-setup",
    "setup.cfg": "python-setup",
    "Pipfile": "python-pipenv",
    "poetry.lock": "python-lockfile",
    "Cargo.toml": "rust-cargo",
    "Cargo.lock": "rust-lockfile",
    "go.mod": "go-module",
    "go.sum": "go-lockfile",
    "pom.xml": "java-maven",
    "build.gradle": "java-gradle",
    "build.gradle.kts": "java-gradle",
    "Gemfile": "ruby-bundler",
    "composer.json": "php-composer",
    "mix.exs": "elixir-mix",
    "deno.json": "deno",
    "deno.jsonc": "deno",
    "Makefile": "make",
    "justfile": "just",
    "Dockerfile": "docker",
    "docker-compose.yml": "docker-compose",
    "docker-compose.yaml": "docker-compose",
    "SKILL.md": "codex-skill",
}

DOC_NAMES = {
    "README",
    "README.md",
    "README.rst",
    "README.txt",
    "CONTRIBUTING.md",
    "ARCHITECTURE.md",
    "DESIGN.md",
    "CHANGELOG.md",
    "AGENTS.md",
    "SECURITY.md",
    "DEVELOPMENT.md",
}

DOC_DIRS = {"docs", "doc", "documentation", "guides", "guide", "manual"}
REFERENCE_DIRS = {"references", "reference"}

ENTRY_FILENAMES = {
    "main.py",
    "app.py",
    "server.py",
    "manage.py",
    "__main__.py",
    "index.js",
    "index.ts",
    "main.js",
    "main.ts",
    "cli.js",
    "cli.ts",
    "server.js",
    "server.ts",
    "main.go",
    "main.rs",
    "lib.rs",
    "mod.rs",
}

ENTRY_DIRS = {"cmd", "bin", "cli", "server", "app", "apps"}
TEST_DIRS = {"test", "tests", "__tests__", "spec", "specs", "e2e", "integration"}
EXAMPLE_DIRS = {"example", "examples", "demo", "demos", "sample", "samples"}
GENERATED_DIRS = {
    "generated",
    "gen",
    "autogen",
    "__generated__",
    "graphql",
    "openapi",
    "proto",
    "protos",
}
GENERATED_SUFFIXES = (
    ".pb.go",
    ".pb.cc",
    ".pb.h",
    ".g.dart",
    ".generated.ts",
    ".generated.js",
    ".gen.ts",
    ".gen.js",
    ".min.js",
    ".min.css",
)
GENERATED_MARKERS = (
    "generated by",
    "auto-generated",
    "autogenerated",
    "do not edit",
    "@generated",
    "code generated",
)

ARCHITECTURE_SIGNAL_RULES = {
    "cli": ("cli", "command", "commands", "argparse", "cobra", "commander", "click"),
    "http": ("router", "route", "routes", "controller", "controllers", "handler", "handlers", "middleware", "server"),
    "public-api": ("api", "client", "sdk", "exports", "index", "lib"),
    "config": ("config", "settings", "options", "env", "environment"),
    "plugin": ("plugin", "plugins", "extension", "extensions", "hook", "hooks"),
    "adapter": ("adapter", "adapters", "provider", "providers", "driver", "drivers"),
    "storage": ("store", "storage", "repository", "repositories", "database", "db", "cache"),
    "queue-or-job": ("queue", "worker", "job", "jobs", "scheduler", "task", "tasks"),
    "parser-or-compiler": ("parser", "lexer", "compiler", "transform", "transforms", "ast", "codegen"),
    "agent-or-tool": ("agent", "tool", "tools", "planner", "executor", "runner"),
    "ui": ("component", "components", "page", "pages", "view", "views", "screen", "screens"),
    "observability": ("log", "logger", "metrics", "telemetry", "trace", "tracing"),
}


DIAGRAM_RULES = {
    "cli": ("flowchart", "command flow from arguments to output"),
    "http": ("sequence", "request path through route, middleware, handler, and response"),
    "public-api": ("flowchart", "public API handoff into core engine"),
    "config": ("flowchart", "configuration loading and precedence"),
    "plugin": ("component", "extension points and plugin lifecycle"),
    "adapter": ("component", "ports, adapters, and external systems"),
    "storage": ("flowchart", "state ownership and persistence boundary"),
    "queue-or-job": ("sequence", "job scheduling, execution, retry, and commit"),
    "parser-or-compiler": ("flowchart", "pipeline from input to intermediate form to output"),
    "agent-or-tool": ("sequence", "intent, planning, tool execution, observation, response"),
    "ui": ("component", "UI state and data ownership"),
    "observability": ("flowchart", "events, logs, metrics, and tracing boundary"),
}


def iter_files(root: Path) -> Iterable[Path]:
    for current, dirs, files in os.walk(root):
        dirs[:] = sorted(d for d in dirs if d not in SKIP_DIRS)
        current_path = Path(current)
        for name in sorted(files):
            path = current_path / name
            if name not in MANIFEST_TYPES and path.suffix in SKIP_SUFFIXES:
                continue
            yield path


def count_lines(path: Path) -> int:
    try:
        with path.open("r", encoding="utf-8", errors="ignore") as handle:
            return sum(1 for _ in handle)
    except OSError:
        return 0


def read_prefix(path: Path, limit: int = 4096) -> str:
    try:
        return path.read_text(encoding="utf-8", errors="ignore")[:limit]
    except OSError:
        return ""


def rel(path: Path, root: Path) -> str:
    return path.relative_to(root).as_posix()


def top_directory(relative: str) -> str:
    parts = Path(relative).parts
    return parts[0] if len(parts) > 1 else "."


def path_parts(relative: str) -> set[str]:
    return {part.lower() for part in Path(relative).parts[:-1]}


def is_test_path(relative: str) -> bool:
    lowered = relative.lower()
    name = Path(lowered).name
    return (
        bool(path_parts(relative) & TEST_DIRS)
        or name.startswith("test_")
        or name.endswith("_test.py")
        or name.endswith(".test.ts")
        or name.endswith(".test.tsx")
        or name.endswith(".test.js")
        or name.endswith(".spec.ts")
        or name.endswith(".spec.tsx")
        or name.endswith(".spec.js")
        or name.endswith("_test.go")
        or name.endswith("_test.rs")
    )


def is_example_path(relative: str) -> bool:
    return bool(path_parts(relative) & EXAMPLE_DIRS)


def is_generated_path(relative: str, path: Path) -> bool:
    lowered = relative.lower()
    if any(part in GENERATED_DIRS for part in path_parts(relative)):
        return True
    if lowered.endswith(GENERATED_SUFFIXES):
        return True
    if path.suffix in {".js", ".ts", ".go", ".py", ".java", ".rs", ".css"}:
        prefix = read_prefix(path, 2048).lower()
        return any(marker in prefix for marker in GENERATED_MARKERS)
    return False


def architecture_signals(relative: str) -> list[str]:
    lowered = relative.lower()
    name = Path(lowered).stem
    tokens = set(path_parts(lowered))
    tokens.update(part for part in name.replace("-", "_").split("_") if part)
    signals = []
    for signal, markers in ARCHITECTURE_SIGNAL_RULES.items():
        if any(marker in tokens or marker in lowered for marker in markers):
            signals.append(signal)
    return sorted(signals)


def manifest_details(path: Path, relative: str) -> dict[str, Any]:
    details: dict[str, Any] = {
        "path": relative,
        "type": MANIFEST_TYPES.get(path.name, "manifest"),
    }
    if path.name == "package.json":
        try:
            data = json.loads(path.read_text(encoding="utf-8", errors="ignore"))
            scripts = data.get("scripts") or {}
            details["name"] = data.get("name")
            details["entry_fields"] = {
                key: data[key]
                for key in ("main", "module", "types", "bin", "exports")
                if key in data
            }
            details["scripts"] = sorted(scripts)[:30]
            details["dependencies"] = len(data.get("dependencies") or {})
            details["dev_dependencies"] = len(data.get("devDependencies") or {})
        except (OSError, json.JSONDecodeError):
            details["parse_error"] = True
    elif path.name == "pyproject.toml" and tomllib:
        try:
            data = tomllib.loads(path.read_text(encoding="utf-8", errors="ignore"))
            project = data.get("project") or {}
            poetry = ((data.get("tool") or {}).get("poetry") or {})
            scripts = project.get("scripts") or poetry.get("scripts") or {}
            details["name"] = project.get("name") or poetry.get("name")
            details["scripts"] = sorted(scripts)[:30] if isinstance(scripts, dict) else []
            details["build_system"] = (data.get("build-system") or {}).get("build-backend")
        except (OSError, ValueError):
            details["parse_error"] = True
    elif path.name == "Cargo.toml" and tomllib:
        try:
            data = tomllib.loads(path.read_text(encoding="utf-8", errors="ignore"))
            package = data.get("package") or {}
            details["name"] = package.get("name")
            details["has_workspace"] = "workspace" in data
            details["bin_targets"] = [
                item.get("name")
                for item in data.get("bin", [])
                if isinstance(item, dict) and item.get("name")
            ][:30]
        except (OSError, ValueError):
            details["parse_error"] = True
    return details


def add_entry(entries: list[dict[str, Any]], path: str, kind: str, reason: str, score: int) -> None:
    entries.append({"path": path, "kind": kind, "reason": reason, "score": score})


def manifest_entries(root: Path, manifest: dict[str, Any]) -> list[dict[str, Any]]:
    entries: list[dict[str, Any]] = []
    manifest_path = manifest["path"]
    base = Path(manifest_path).parent
    if str(base) == ".":
        base = Path("")

    fields = manifest.get("entry_fields") or {}
    for key, value in fields.items():
        values = value if isinstance(value, list) else [value]
        if isinstance(value, dict):
            values = [v for v in value.values() if isinstance(v, str)]
        for item in values:
            if not isinstance(item, str) or item.startswith(".") and len(item) == 1:
                continue
            candidate = (base / item).as_posix().lstrip("./")
            if (root / candidate).exists():
                add_entry(entries, candidate, "manifest-entry", f"{manifest_path} field `{key}`", 95)

    for script in manifest.get("scripts") or []:
        if script in {"start", "dev", "serve", "test", "build", "cli"}:
            add_entry(entries, manifest_path, "manifest-script", f"script `{script}`", 60)

    return entries


def entry_score(relative: str, language: str | None) -> tuple[int, str] | None:
    name = Path(relative).name
    parts = path_parts(relative)
    if name == "SKILL.md":
        return 90, "Codex skill entrypoint"
    if name in ENTRY_FILENAMES:
        return 80, f"conventional {name} entry file"
    if "cmd" in parts and name == "main.go":
        return 95, "Go command entry under cmd/"
    if "src" in parts and name in {"lib.rs", "main.rs"}:
        return 85, f"Rust {name} root"
    if parts & ENTRY_DIRS and language in {"Python", "JavaScript", "TypeScript", "Go", "Rust"}:
        return 55, "file lives under an entry-like directory"
    return None


def doc_kind(relative: str) -> str:
    name = Path(relative).name.upper()
    if name == "SKILL.MD":
        return "skill-entry"
    if name.startswith("README"):
        return "readme"
    if "ARCHITECTURE" in name or "DESIGN" in name:
        return "architecture"
    if "CONTRIBUTING" in name or "DEVELOPMENT" in name:
        return "developer-guide"
    if "CHANGELOG" in name:
        return "change-log"
    if top_directory(relative).lower() in REFERENCE_DIRS:
        return "reference"
    if top_directory(relative).lower() in DOC_DIRS:
        return "docs-tree"
    return "documentation"


def summarize_core_directories(files: list[dict[str, Any]]) -> list[dict[str, Any]]:
    buckets: dict[str, dict[str, Any]] = {}
    for item in files:
        directory = item["top_directory"]
        bucket = buckets.setdefault(
            directory,
            {
                "directory": directory,
                "files": 0,
                "code_lines": 0,
                "total_lines": 0,
                "languages": {},
                "signals": set(),
                "architecture_signals": set(),
            },
        )
        bucket["files"] += 1
        bucket["total_lines"] += item["lines"]
        language = item["language"]
        if language != "Other" and language != "Markdown":
            bucket["code_lines"] += item["lines"]
            bucket["languages"][language] = bucket["languages"].get(language, 0) + item["lines"]
        if item["is_test"]:
            bucket["signals"].add("tests")
        if item["is_generated"]:
            bucket["signals"].add("generated")
        if item["is_example"]:
            bucket["signals"].add("examples")
        if item["is_doc"]:
            bucket["signals"].add("docs")
        bucket["architecture_signals"].update(item.get("architecture_signals", []))

    result = []
    for bucket in buckets.values():
        signals = bucket["signals"]
        score = bucket["code_lines"]
        if bucket["directory"] in {".", "src", "lib", "packages", "apps", "cmd", "internal"}:
            score += 500
        if "tests" in signals:
            score -= int(bucket["code_lines"] * 0.5)
        if "generated" in signals:
            score -= int(bucket["code_lines"] * 0.7)
        if "docs" in signals and bucket["code_lines"] < 100:
            score -= 300
        if bucket["directory"] == "." and bucket["code_lines"] == 0:
            score = min(score, 100)
        result.append(
            {
                "directory": bucket["directory"],
                "files": bucket["files"],
                "code_lines": bucket["code_lines"],
                "total_lines": bucket["total_lines"],
                "languages": [
                    {"language": name, "lines": lines}
                    for name, lines in sorted(bucket["languages"].items(), key=lambda x: x[1], reverse=True)
                ][:5],
                "signals": sorted(signals),
                "architecture_signals": sorted(bucket["architecture_signals"]),
                "score": score,
            }
        )
    return sorted(result, key=lambda item: item["score"], reverse=True)


def summarize_architecture_signals(files: list[dict[str, Any]]) -> list[dict[str, Any]]:
    buckets: dict[str, dict[str, Any]] = {}
    for item in files:
        if item["is_generated"]:
            continue
        for signal in item.get("architecture_signals", []):
            bucket = buckets.setdefault(signal, {"signal": signal, "files": 0, "lines": 0, "sample": []})
            bucket["files"] += 1
            bucket["lines"] += item["lines"]
            if len(bucket["sample"]) < 12:
                bucket["sample"].append(item["path"])
    return sorted(buckets.values(), key=lambda item: (-item["files"], -item["lines"], item["signal"]))


def diagram_suggestions(signals: list[dict[str, Any]], entries: list[dict[str, Any]]) -> list[dict[str, Any]]:
    suggestions = []
    seen = set()
    for item in signals:
        signal = item["signal"]
        if signal not in DIAGRAM_RULES or signal in seen:
            continue
        kind, reason = DIAGRAM_RULES[signal]
        suggestion = {
            "kind": kind,
            "focus": signal,
            "why": reason,
            "evidence_sample": item.get("sample", [])[:5],
        }
        suggestions.append(suggestion)
        seen.add(signal)
    if entries and "entry-flow" not in seen:
        suggestions.insert(
            0,
            {
                "kind": "flowchart",
                "focus": "entry-flow",
                "why": "main entry path from public surface to core behavior",
                "evidence_sample": [entry["path"] for entry in entries[:5]],
            },
        )
    return suggestions[:8]


def build_reading_route(
    docs: list[dict[str, Any]],
    manifests: list[dict[str, Any]],
    entries: list[dict[str, Any]],
    core_dirs: list[dict[str, Any]],
    largest_files: list[dict[str, Any]],
) -> list[dict[str, str]]:
    route: list[dict[str, str]] = []
    if docs:
        first_doc = next((doc for doc in docs if doc["kind"] == "readme"), docs[0])
        route.append({"target": first_doc["path"], "why": "orientation and project intent"})
    for manifest in manifests[:3]:
        route.append({"target": manifest["path"], "why": "runtime, dependency, and command surface"})
    for entry in entries[:5]:
        route.append({"target": entry["path"], "why": entry["reason"]})
    for directory in core_dirs[:5]:
        if directory["directory"] != "." and directory["score"] > 0:
            route.append({"target": directory["directory"], "why": "high-signal implementation area"})
    for item in largest_files[:3]:
        route.append({"target": item["path"], "why": "large source file worth skimming for responsibility boundaries"})

    seen = set()
    compact = []
    for item in route:
        if item["target"] in seen:
            continue
        seen.add(item["target"])
        compact.append(item)
    return compact[:18]


def scan(root: Path) -> dict[str, Any]:
    root = root.resolve()
    files: list[dict[str, Any]] = []
    language_lines: dict[str, int] = {}
    directory_lines: dict[str, int] = {}
    manifests: list[dict[str, Any]] = []
    docs: list[dict[str, Any]] = []
    entry_candidates: list[dict[str, Any]] = []
    test_files: list[str] = []
    generated_files: list[str] = []
    example_files: list[str] = []

    for path in iter_files(root):
        relative = rel(path, root)
        lines = count_lines(path)
        suffix = path.suffix
        language = LANG_BY_SUFFIX.get(suffix)
        directory = top_directory(relative)
        is_test = is_test_path(relative)
        is_doc = (
            path.name in DOC_NAMES
            or path.name == "SKILL.md"
            or directory.lower() in DOC_DIRS
            or directory.lower() in REFERENCE_DIRS
        )
        is_example = is_example_path(relative)
        is_generated = is_generated_path(relative, path)
        arch_signals = architecture_signals(relative)
        record = {
            "path": relative,
            "lines": lines,
            "language": language or "Other",
            "top_directory": directory,
            "is_test": is_test,
            "is_doc": is_doc,
            "is_example": is_example,
            "is_generated": is_generated,
            "architecture_signals": arch_signals,
        }
        files.append(record)
        directory_lines[directory] = directory_lines.get(directory, 0) + lines
        if language:
            language_lines[language] = language_lines.get(language, 0) + lines
        if path.name in MANIFEST_TYPES:
            manifest = manifest_details(path, relative)
            manifests.append(manifest)
            entry_candidates.extend(manifest_entries(root, manifest))
        if is_doc:
            docs.append({"path": relative, "kind": doc_kind(relative), "lines": lines})
        scored_entry = entry_score(relative, language)
        if scored_entry:
            score, reason = scored_entry
            add_entry(entry_candidates, relative, "file", reason, score)
        if is_test:
            test_files.append(relative)
        if is_generated:
            generated_files.append(relative)
        if is_example:
            example_files.append(relative)

    entry_candidates = sorted(
        {entry["path"] + entry["reason"]: entry for entry in entry_candidates}.values(),
        key=lambda item: (-item["score"], item["path"]),
    )[:100]
    largest_files = sorted(
        [item for item in files if not item["is_generated"]],
        key=lambda item: item["lines"],
        reverse=True,
    )[:30]
    language_summary = [
        {"language": name, "lines": lines}
        for name, lines in sorted(language_lines.items(), key=lambda item: item[1], reverse=True)
    ]
    directory_summary = [
        {"directory": name, "lines": lines}
        for name, lines in sorted(directory_lines.items(), key=lambda item: item[1], reverse=True)
    ]
    core_dirs = summarize_core_directories(files)[:20]
    arch_signal_summary = summarize_architecture_signals(files)

    return {
        "root": root.as_posix(),
        "total_files": len(files),
        "total_lines": sum(item["lines"] for item in files),
        "languages": language_summary,
        "top_directories": directory_summary,
        "core_directories": core_dirs,
        "manifests": sorted(manifests, key=lambda item: item["path"]),
        "documentation": sorted(docs, key=lambda item: (item["kind"] != "readme", item["path"]))[:120],
        "entry_candidates": entry_candidates,
        "architecture_signals": arch_signal_summary,
        "diagram_suggestions": diagram_suggestions(arch_signal_summary, entry_candidates),
        "tests": {
            "count": len(test_files),
            "sample": sorted(test_files)[:100],
        },
        "generated_code": {
            "count": len(generated_files),
            "sample": sorted(generated_files)[:100],
        },
        "examples": {
            "count": len(example_files),
            "sample": sorted(example_files)[:80],
        },
        "largest_files": largest_files,
        "reading_route": build_reading_route(
            docs,
            sorted(manifests, key=lambda item: item["path"]),
            entry_candidates,
            core_dirs,
            largest_files,
        ),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Scan a repository for code research.")
    parser.add_argument("repo", help="Path to the repository")
    parser.add_argument("--out", help="Output JSON path. Defaults to stdout.")
    args = parser.parse_args()

    root = Path(args.repo)
    if not root.exists() or not root.is_dir():
        parser.error(f"repo path does not exist or is not a directory: {root}")

    result = scan(root)
    payload = json.dumps(result, ensure_ascii=False, indent=2)
    if args.out:
        out = Path(args.out)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(payload + "\n", encoding="utf-8")
    else:
        print(payload)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
